services:
  postgres:
    build:
      context: docker
      dockerfile: postgres/postgres.dockerfile
    environment:
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data-nocache
    volumes:
      - ./docker/postgres/db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
  pgadmin:
    image: dpage/pgadmin4:9.3.0
    restart: "no"
    ports:
      - ${PG_ADMIN_PORT}:80
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/pgpass:/pgadmin4/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/pgpass; /entrypoint.sh;"
  authDb:
    image: postgres:17.5
    restart: "no"
    ports:
      - ${POSTGRES_AUTH_PORT}:5432
    volumes:
      - ./docker/postgres/authDb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      POSTGRES_AUTH_DB: telegram_birthdate
      PG_DATA: /var/lib/postgresql/data-nocache
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    restart: "no"
    command:
      - "start-dev"
    ports:
      - ${KEYCLOAK_PORT}:9080
    environment:
      KC_HTTP_PORT: 9080
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB_URL: jdbc:postgresql://authDb:5432/${POSTGRES_AUTH_DB}
      KC_DB: postgres
      KC_DB_URL_HOST: authDb
      KC_DB_URL_PORT: ${POSTGRES_AUTH_PORT}
      KC_DB_URL_DATABASE: ${POSTGRES_AUTH_DB}
      KC_DB_USERNAME: ${POSTGRES_AUTH_USER}
      KC_DB_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test:
        [ "CMD-SHELL", "{ exec 3<>/dev/tcp/localhost/9000 && echo -e \"GET /health/ready HTTP/1.1\nhost: localhost:9000\n\" >&3 && timeout --preserve-status 1 cat <&3 | grep -m 1 -q 'status.*UP'; }" ]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
    depends_on:
      - authDb
networks:
  notification_telegram:
    driver: bridge